enactjs/performance-tests

performance/tests/VirtualList.test.js, performance/utils.js, src/App/App.js, src/views/ScrollerPanel.js, src/views/VirtualList.js
Added basic tests for VirtualList. Also changed the way we do mouse wheeling that is easier and more customizable.
=> Added Tests for VirtualList and Updated Scroller

jest.config.js, jest.setup.js, package.json, performance/TestResults.js, performance/tests/Scroller.test.js, performance/tests/VirtualList.test.js
Added test all command
Added logging after each test. This should be better in the future, but for now before infrastructure is build we can just use this.
Also made a 30 second timeout. This should help avoid the jest timeout errors with 5000ms.
=> added test-all command

performance/tests/Scroller.test.js, performance/tests/VirtualList.test.js
had some copy paste stuff. I'm just gonna merge this in a quick cleanup.
=> Changed some types for logging

performance/tests/ViewManager.test.js, src/App/App.js, src/views/ViewManager.js
Enact-DCO-1.0-Signed-off-by: Stephen Choi <stephen.choi@lge.com>
=> Add ViewManager perf test

performance/tests/Image.test.js, performance/tests/ImageItem.test.js, src/App/App.js, src/views/Image.js, src/views/ImageItem.js
Added performance tests for Image and ImageItem components.
=> WRN-6792: Add puppeteer tests to Image and ImageItem

performance/tests/Dropdown.test.js, performance/tests/FormCheckboxItem.test.js, src/App/App.js, src/views/Dropdown.js, src/views/FormCheckboxItem.js
Added performance tests for Dropdown and FormCheckboxItem
=> WRN-6794: Add puppeteer tests to Dropdown and FormCheckboxItem

performance/tests/Scroller.test.js, performance/tests/Slider.test.js, performance/tests/Switch.test.js, performance/tests/SwitchItem.test.js, src/App/App.js, src/components/MultipleComponents.js, src/views/ScrollerMultipleChildren.js, src/views/ScrollerPanel.js, src/views/Slider.js, src/views/Switch.js
Added performance tests for Slider and Scroller components.
=> WRN-6803: Added performance tests for Slider and Scroller

performance/tests/Icon.test.js, src/App/App.js, src/views/Icon.js, src/views/Item.js
Added performance tests for Icon and Item
=> WRN-6796: Add puppeteer tests to Icon and Item

performance/tests/DayPicker.test.js, performance/tests/Dropdown.test.js, performance/tests/RangePicker.test.js, src/App/App.js, src/views/DayPicker.js, src/views/FormCheckboxItem.js, src/views/RangePicker.js
Added performance tests for DayPicker and RangePicker
Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com
=> WRN-6804: Added performance tests for DayPicker and RangePicker

package.json, performance/TestResults.js, performance/TraceModel.js, performance/tests/Button.test.js, puppeteer.setup.js, src/views/Button.js
**Calculation of LCP by reading the puppeteer tracing files
Calculation of CLS and FID using the PerformanceObserver API. 
Own calculation of FPS, using requestAnimationFrame(). No  npm dependency is used.
Removed testing of Mount and Update times
Removed devtools-timeline-model dependency
Added timestamp in the logs. log file is not reset on every test. The data is now being appended.**
WRN-8017
Enact-DCO-1.0-Signed-off-by: …
=> WRN-8017: Added new function for FPS, LCP, FID, CLS

performance/tests/ProgressBar.test.js, performance/tests/ProgressButton.test.js, src/App/App.js, src/views/ProgressBar.js, src/views/ProgressButton.js
Created performance tests for ProgressBar and ProgressButton.
WRN-6802
Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
=> WRN-6802: Added performance tests for ProgressBar and ProgressButton.

package.json, performance/tests/Marquee.test.js
Replaced concurrently with npm-run-all dependecy in package.json
Updated script `test-all` to use `npm-run-all` command
Fixed tests for Marquee to create testResults file when it does not exist.
WRN-10939
Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com
=> WRN-10939: Replaced concurrently with npm-run-all dependency in package.json. Fixed bug in Marquee tests

performance/tests/VideoPlayer.test.js, src/views/MediaOverlay.js, src/views/VideoPlayer.js
Changed video source for VideoPlayer and MediaOverlay view in order to make it work with chromium
Fixed tests for VideoPlayer: Focus changed on "Next" button because the video plays automatically. Added a timeout in the CLs test
WRN-13491
Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com
=> WRN-13491: Fixed tests and view for VideoPlayer. Fixed view for MediaOverlay

performance/tests/OverallView.test.js, performanceMetrics/src/App/App.js, performanceMetrics/src/views/Chart.js, src/App/App.js, src/views/OverallView.js
added view for multiple components
updated metrics app to include this new view.
updated range for charts and fixed minor bug when component is changed
WRN-15813
Enact-DCO-1.0-Signed-off-by: Daniel Stoian daniel.stoian@lgepartner.com
=> WRN-15813: Added view with multiple "heavy" components and updated metrics app

src/views/OverallView.js, src/views/Panels.js, src/views/TabLayout.js
Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com
Changed image service.
WRN-17786
=> WRN-17786: Changed Placehold.it Image service

package.json, performanceMetrics/package.json, src/App/App.js
WRP-3071
Enact-DCO-1.0-Signed-off-by: Daniel Stoian (daniel.stoian@lgepartner.com)
=> WRP-3071: Updated dependencies to fix security vulnerabilities

performanceMetrics/package.json, performanceMetrics/src/App/App.js
Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com
Replaced `axios` with `fetch` native API in performanceMetrics app
WRP-10556
=> WRP-10556: Replace axios with fetch in PerformanceMetrics app

package.json, performance/TestResults.js, puppeteer.setup.js, src/App/App.js, src/components/MultipleComponents.js, src/views/FixedPopupPanels.js, src/views/FlexiblePopupPanels.js, src/views/MarqueeMultiple.js, src/views/ScrollerMultipleChildren.js
Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com
Upgrade dependencies to major versions. 
Performed upgrades and code adjustments, where necessary, for:
**"node-fetch": "^3.3.1"** - latest version, required just changing the 'node-fetch' import to a dynamic import
**"react-router-dom": "^6.9.0"** - latest version, required some code refactoring to use '<Routes>', 'element' and 'useLocation' hook
**"jest": "^28.1.3"** - upgraded to latest version that still supports node v12 (could not upgrade to v29.5.0: https://github.com/facebook/jest/blob/main/CHANGELOG.md, PR: …
=> WRP-10559: Update dependencies to new major version

package.json, performanceMetrics/package.json
Some dependencies need major update.
WRP-3072
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-3072: Updated dependencies to fix security vulnerabilities

package.json, performanceMetrics/package.json
Dependencies now use the latest minor version.
Some dependencies need major update.
They will be handled in separate tickets.
There were no breaking changes affecting this repo.
WRP-17865
https://github.com/motdotla/dotenv/releases
https://github.com/remix-run/react-router/releases
https://github.com/recharts/recharts/releases
Enact-DCO-1.0-Signed-off-by: Andrei Tirla …
=> WRP-17865: Updated dependencies to fix security vulnerabilities

.gitignore, package-lock.json, package.json
Updated dependencies for `jest` and `jest-environment-jsdom` to the latest major version `^19.6.1`.
We are now using the latest major version.
There were no breaking changes affecting our code.
https://github.com/jestjs/jest/releases?page=2
WRP-19322
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-19322: Updated `jest` and `jest-environment-jsdom` to the latest major version

package-lock.json, package.json, performanceMetrics/package.json
Dependencies now use the latest minor version.
Some dependencies need major update.
They will be handled in separate tickets.
There were no breaking changes affecting this repo.
WRP-17866
https://github.com/remix-run/react-router/releases
https://github.com/recharts/recharts/releases
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-17866: Updated minor dependencies to fix vulnerabilities

package-lock.json, package.json, performanceMetrics/package.json
Dependencies now use the latest minor version.
There were no breaking changes affecting this repo.
WRP-28228
https://github.com/remix-run/react-router/releases
https://github.com/jestjs/jest/releases
https://github.com/recharts/recharts/releases
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com
=> WRP-28228: Update minor dependencies to fix vulnerabilities

package-lock.json, package.json
Update package dependencies to fix security vulnerabilities
WRQ-3494
Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com
=> WRQ-3494: Update package dependencies to fix security vulnerabilities

package-lock.json, package.json, performanceMetrics/package.json
There were no breaking changes affecting this repo
WRQ-8581
Enact-DCO-1.0-Signed-off-by: Daniel Stoian (daniel.stoian@lgepartner.com)
=> WRQ-8581: Updated dependencies to fix vulnerabilities

performanceMetrics/src/views/Chart.js
Changed chart configuration to show all labels and lines
Changed chart configuration to show all labels and lines
WRQ-18593
Enact-DCO-1.0-Signed-off-by: Daniel Stoian (daniel.stoian@lgepartner.com)
=> WRQ-18593: Changed chart configuration to show all labels and lines

package.json
Fixed resolution independence on Sandstone views with `enact link`
Reverted `enact.theme` from package.json back to "sandstone"
WRQ-20077
Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com
=> WRQ-20077: Fix resolution independence on Sandstone views with `enact link`

package-lock.json, package.json, performanceMetrics/package.json
Updated dependencies to the latest minor version.
Updated dependencies to the latest minor version.
WRQ-25865
Enact-DCO-1.0-Signed-off-by: Ion Andrusciac ion.andrusciac@lgepartner.com
=> WRQ-25865: Updated package dependencies to fix security vulnerabilities

package-lock.json, package.json, performance/tests/agate/CheckboxItem.test.js, performance/tests/agate/MediaPlayer.test.js, performance/tests/sandstone/FlexiblePopupPanels.test.js, performanceMetrics/package.json, puppeteer.setup.js
Updated dependencies minor versions
Updated dependencies minor versions
Fixed "'left' is not pressed" warning for some components.
WRR-10055
Enact-DCO-1.0-Signed-off-by: Paul Beldean paul.beldean@lgepartner.com
=> WRR-10055: Updated package dependencies to fix security vulnerabilities

package.json, performanceMetrics/package.json
We have already implemented eslint 9, and going forward, configs other than eslint.config.js (eslintrc files, eslintignore files, package.json, etc.) will no longer work.
Remove eslint-related configs in package.json
WRR-22888
Enact-DCO-1.0-Signed-off-by: Taeyoung Hong (taeyoung.hong@lge.com)
=> WRR-22888: Remove eslint-related configs in package.json

package-lock.json, package.json, performance/TestResults.js, performanceMetrics/package.json
Updated node modules` major versions
- dotenv                                      ^16.4.7 → ^17.0.1
- jest                                            ^29.7.0  →  ^30.0.0
- jest-environment-jsdom          ^29.7.0  →  ^30.0.0
- shelljs                                        ^0.9.2  →  ^0.10.0
- performanceMetrics: recharts ^2.15.1  →    ^3.0.2
Breaking Changes
- dotenv: [Breaking Changes/Release Notes](https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md)
- …
=> WRR-28729: Updated node modules` major versions

package-lock.json, package.json, puppeteer.setup.js
Updated dependencies to fix vulnerabilities
Updated dependencies to fix vulnerabilities
Changed headless mode because some tests were failing because of timeout
NXT-743
Enact-DCO-1.0-Signed-off-by: Daniel Stoian (daniel.stoian@lgepartner.com)
=> NXT-743: Updated dependencies to fix vulnerabilities
